"""uuid´s fields change

Revision ID: 279f716380f3
Revises: 95a9e543040e
Create Date: 2025-05-30 20:55:56.183465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '279f716380f3'
down_revision: Union[str, None] = '95a9e543040e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashesdetails', 'cash_details_id',
               existing_type=sa.UUID(),
               comment='The primary key of the cash_details table',
               existing_nullable=False)
    op.drop_constraint('chat_chat_id_key', 'chat', type_='unique')
    op.alter_column('chatmessages', 'message_id',
               existing_type=sa.UUID(),
               comment='The primary key of the chat_messages table',
               existing_nullable=False)
    op.drop_constraint('departments_department_id_key', 'departments', type_='unique')
    op.drop_constraint('services_service_id_key', 'services', type_='unique')
    op.drop_constraint('specialties_specialty_id_key', 'specialties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('specialties_specialty_id_key', 'specialties', ['specialty_id'])
    op.create_unique_constraint('services_service_id_key', 'services', ['service_id'])
    op.create_unique_constraint('departments_department_id_key', 'departments', ['department_id'])
    op.alter_column('chatmessages', 'message_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The primary key of the chat_messages table',
               existing_nullable=False)
    op.create_unique_constraint('chat_chat_id_key', 'chat', ['chat_id'])
    op.alter_column('cashesdetails', 'cash_details_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The primary key of the cash_details table',
               existing_nullable=False)
    # ### end Alembic commands ###
