"""fix(appointment relationship with cashes_details)

Revision ID: 3bf54f1829a9
Revises: 99af21e3cc34
Create Date: 2025-08-13 20:01:32.630926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf54f1829a9'
down_revision: Union[str, None] = '99af21e3cc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashesdetails')
    op.create_unique_constraint(None, 'cash_details', ['cash_details_id'])
    op.drop_constraint('cashes_appointment_id_fkey', 'cashes', type_='foreignkey')
    op.drop_column('cashes', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashes', sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('cashes_appointment_id_fkey', 'cashes', 'appointments', ['appointment_id'], ['appointment_id'])
    op.drop_constraint(None, 'cash_details', type_='unique')
    op.create_table('cashesdetails',
    sa.Column('cash_details_id', sa.UUID(), autoincrement=False, nullable=False, comment='The primary key of the cash_details table'),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_transaction', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cash_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['cashes.cash_id'], name='cashesdetails_cash_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='cashesdetails_service_id_fkey'),
    sa.PrimaryKeyConstraint('cash_details_id', name='cashesdetails_pkey'),
    sa.UniqueConstraint('cash_details_id', name='cashesdetails_cash_details_id_key')
    )
    # ### end Alembic commands ###
