"""Descripción de los cambios

Revision ID: 441c9277c345
Revises: 758c49703aff
Create Date: 2025-07-28 19:18:07.570144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '441c9277c345'
down_revision: Union[str, None] = '758c49703aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('url_image_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('url_image_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_image_profile')
    op.drop_column('doctors', 'url_image_profile')
    # ### end Alembic commands ###
