"""available turn field

Revision ID: 45d5b7a11242
Revises: 67cbce1aa404
Create Date: 2025-05-14 14:57:52.934612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45d5b7a11242'
down_revision: Union[str, None] = '67cbce1aa404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_schedules', sa.Column('available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_schedules', 'available')
    # ### end Alembic commands ###
