"""initial migration

Revision ID: 598065897212
Revises: 
Create Date: 2025-04-27 01:55:39.332342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '598065897212'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_limit', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'appointments', ['appointment_id'])
    op.create_unique_constraint(None, 'cashes', ['cash_id'])
    op.create_unique_constraint(None, 'cashesdetails', ['cash_details_id'])
    op.create_unique_constraint(None, 'chat', ['chat_id'])
    op.create_unique_constraint(None, 'chatmessages', ['message_id'])
    op.create_unique_constraint(None, 'departments', ['department_id'])
    op.create_unique_constraint(None, 'doctors', ['doctor_id'])
    op.create_unique_constraint(None, 'locations', ['location_id'])
    op.create_unique_constraint(None, 'services', ['service_id'])
    op.create_unique_constraint(None, 'specialties', ['specialty_id'])
    op.create_unique_constraint(None, 'turns', ['turn_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'turns', type_='unique')
    op.drop_constraint(None, 'specialties', type_='unique')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'chatmessages', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    op.drop_constraint(None, 'cashesdetails', type_='unique')
    op.drop_constraint(None, 'cashes', type_='unique')
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_column('appointments', 'date_limit')
    # ### end Alembic commands ###
