"""initial migration

Revision ID: 5ecc79925906
Revises: 
Create Date: 2025-04-25 15:12:43.275569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ecc79925906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('doc_1_id', sa.Uuid(), nullable=False),
    sa.Column('doc_2_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('medical_schedules',
    sa.Column('medical_schedule_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('medical_schedule_id')
    )
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chatmessages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_id')
    )
    op.create_table('specialties',
    sa.Column('specialty_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialty_id'),
    sa.UniqueConstraint('specialty_id')
    )
    op.create_table('doctors',
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('speciality_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialties.specialty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_table('services',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('specialty_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.specialty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('doctor_medical_schedule_link',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('medical_schedule_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_schedule_id'], ['medical_schedules.medical_schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'medical_schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_medical_schedule_link')
    op.drop_table('services')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_table('specialties')
    op.drop_table('departments')
    op.drop_table('chatmessages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('medical_schedules')
    op.drop_table('locations')
    op.drop_table('chat')
    # ### end Alembic commands ###
