"""initial migration

Revision ID: 67cbce1aa404
Revises: 13ff8febe410
Create Date: 2025-05-10 00:08:20.105796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67cbce1aa404'
down_revision: Union[str, None] = '13ff8febe410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('turn_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'turns', ['turn_id'], ['turn_id'])
    op.drop_constraint('turns_appointment_id_fkey', 'turns', type_='foreignkey')
    op.drop_column('turns', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('turns_appointment_id_fkey', 'turns', 'appointments', ['appointment_id'], ['appointment_id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'turn_id')
    # ### end Alembic commands ###
