"""implement discount in cahs details model

Revision ID: 7249316716d1
Revises: d7fc143d42b3
Create Date: 2025-08-13 19:26:54.173568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7249316716d1'
down_revision: Union[str, None] = 'd7fc143d42b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashesdetails', sa.Column('discount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashesdetails', 'discount')
    # ### end Alembic commands ###
