"""delete and add tieme field in turns

Revision ID: 78450d1c73c3
Revises: 3bf54f1829a9
Create Date: 2025-08-18 19:30:22.565278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78450d1c73c3'
down_revision: Union[str, None] = '3bf54f1829a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashesdetails')
    op.add_column('turns', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashesdetails',
    sa.Column('cash_details_id', sa.UUID(), autoincrement=False, nullable=False, comment='The primary key of the cash_details table'),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_transaction', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cash_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cash_id'], ['cashes.cash_id'], name='cashesdetails_cash_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='cashesdetails_service_id_fkey'),
    sa.PrimaryKeyConstraint('cash_details_id', name='cashesdetails_pkey')
    )
    op.drop_column('turns', 'time')
    # ### end Alembic commands ###
