"""feacture(append state for doctor model)

Revision ID: 7d6a2505906a
Revises: a5f3c8e9d06b
Create Date: 2025-08-06 19:36:58.578277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d6a2505906a'
down_revision: Union[str, None] = 'a5f3c8e9d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    #op.execute("CREATE TYPE doctorstates AS ENUM ('available', 'busy', 'offline')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('state', sa.Enum('available', 'busy', 'offline', name='doctorstates'), nullable=False, server_default='available'))
    op.drop_constraint('turns_service_id_fkey', 'turns', type_='foreignkey')
    op.drop_column('turns', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('turns_service_id_fkey', 'turns', 'services', ['service_id'], ['service_id'])
    op.drop_column('doctors', 'state')
    # ### end Alembic commands ###
