"""total expense for benefit service in cashe details

Revision ID: 99af21e3cc34
Revises: 7249316716d1
Create Date: 2025-08-13 19:49:32.732202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99af21e3cc34'
down_revision: Union[str, None] = '7249316716d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashesdetails', sa.Column('total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashesdetails', 'total')
    # ### end Alembic commands ###
