"""implement turn-service link

Revision ID: a5f3c8e9d06b
Revises: c14a4633bac9
Create Date: 2025-08-04 18:09:16.173768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5f3c8e9d06b'
down_revision: Union[str, None] = 'c14a4633bac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turns_services_link',
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns_services_link', if_exists=True)
    # ### end Alembic commands ###
