"""implement icons fields

Revision ID: c14a4633bac9
Revises: 441c9277c345
Create Date: 2025-08-04 16:45:09.697883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c14a4633bac9'
down_revision: Union[str, None] = '441c9277c345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('icon_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'icon_code')
    # ### end Alembic commands ###
