"""seguro de salud incluido

Revision ID: d53e602779d3
Revises: e716bbce6a07
Create Date: 2025-05-16 14:31:19.939474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd53e602779d3'
down_revision: Union[str, None] = 'e716bbce6a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'healthinsurance', ['health_insurance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'healthinsurance', type_='unique')
    # ### end Alembic commands ###
