"""generate link for turns and schedules

Revision ID: d7fc143d42b3
Revises: e865e9287121
Create Date: 2025-08-12 17:19:09.366314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7fc143d42b3'
down_revision: Union[str, None] = 'e865e9287121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turns_schedules_link',
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('medical_schedule_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medical_schedule_id'], ['medical_schedules.medical_schedule_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id', 'medical_schedule_id')
    )
    op.add_column('medical_schedules', sa.Column('max_patients', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_schedules', 'max_patients')
    op.drop_table('turns_schedules_link')
    # ### end Alembic commands ###
