"""add time field in turns model

Revision ID: e865e9287121
Revises: f6823a63516a
Create Date: 2025-08-11 17:04:12.952286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e865e9287121'
down_revision: Union[str, None] = 'f6823a63516a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turns', 'time',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turns', 'time',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
